export { default as IconEllipsis } from "./icon-ellipsis.svg";
export { default as IconEllipsisWhite } from "./icon-ellipsis-white.svg";
export { default as IconExercise } from "./icon-exercise.svg";
export { default as IconPlay } from "./icon-play.svg";
export { default as IconSelfCare } from "./icon-self-care.svg";
export { default as IconSocial } from "./icon-social.svg";
export { default as IconStudy } from "./icon-study.svg";
export { default as IconWork } from "./icon-work.svg";
export { default as ImageJeremy } from "./image-jeremy.png";
